name: Deploy
on:
  push:
    branches: ["deploy"]
  runs-on: ubuntu-latest
  jobs:
    steps:
      - uses: actions/checkout@v3
      - name: Upload Files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
